import React, { useState, useEffect } from 'react';
import {
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  ScrollView,
  ActivityIndicator,
  Modal,
  TextInput,
  Alert,
  Linking,
  Share,
} from 'react-native';
import { Users, Plus, DollarSign, FileText, CheckCircle2, MessageCircle, Clock, Calendar, ShieldCheck } from 'lucide-react-native';
import { apiClient } from '../lib/apiClient';
import { useTheme } from '../theme/themeSystem';
import { useTranslation } from '../theme/i18n';

const UsersIcon = Users as any;
const PlusIcon = Plus as any;
const MessageCircleIcon = MessageCircle as any;
const ClockIcon = Clock as any;
const CalendarIcon = Calendar as any;

export function PayrollScreen() {
  const { theme, accentHex } = useTheme();
  const { t } = useTranslation();
  const [activeTab, setActiveTab] = useState<'pagar' | 'history'>('pagar');
  const [loading, setLoading] = useState(false);
  const [payrolls, setPayrolls] = useState<any[]>([]);
  const [pagarData, setPagarData] = useState<any | null>(null);
  const [addVisible, setAddVisible] = useState(false);
  const [advanceVisible, setAdvanceVisible] = useState(false);
  const [selectedStaffForAdvance, setSelectedStaffForAdvance] = useState<any | null>(null);
  const [advanceAmount, setAdvanceAmount] = useState('');
  const [advanceReason, setAdvanceReason] = useState('Personal Need');

  // Single Record Entry State
  const [month, setMonth] = useState('2026-08');
  const [empName, setEmpName] = useState('');
  const [designation, setDesignation] = useState('');
  const [basicSalary, setBasicSalary] = useState('');
  const [allowances, setAllowances] = useState('');
  const [deductions, setDeductions] = useState('');

  useEffect(() => {
    fetchPayroll();
    fetchPagarKhata();
  }, []);

  const fetchPayroll = async () => {
    try {
      const res = await apiClient.get('/api/payroll');
      if (res.ok) setPayrolls(await res.json());
    } catch (e) {
      console.warn('Failed to fetch payroll:', e);
    }
  };

  const fetchPagarKhata = async () => {
    setLoading(true);
    try {
      const res = await apiClient.get('/business/pagar-khata');
      if (res.ok) {
        setPagarData(await res.json());
      }
    } catch (e) {
      console.warn('Failed to fetch pagar khata:', e);
    } finally {
      setLoading(false);
    }
  };

  const handleRecordAdvance = async () => {
    if (!selectedStaffForAdvance || !advanceAmount || isNaN(Number(advanceAmount))) {
      Alert.alert('Invalid Amount', 'Please specify a valid advance amount.');
      return;
    }

    try {
      const res = await apiClient.post('/business/pagar-khata/advance', {
        staffId: selectedStaffForAdvance.id,
        amount: Number(advanceAmount),
        reason: advanceReason || 'Personal Advance',
      });
      if (res.ok) {
        Alert.alert('Advance Logged', `₹${advanceAmount} advance recorded and deducted from monthly net salary.`);
        setAdvanceVisible(false);
        setAdvanceAmount('');
        fetchPagarKhata();
      }
    } catch (e: any) {
      Alert.alert('Error', e.message || 'Failed to record advance');
    }
  };

  const handleSendWhatsAppPayslip = async (staffMember: any) => {
    const text = staffMember.whatsAppSummary || 
      `*Pagar Khata Payslip - ${staffMember.name}*\n` +
      `Base: ₹${staffMember.monthlySalary}\n` +
      `Attendance: ${staffMember.attendance?.present || 26}P / ${staffMember.attendance?.absent || 0}A\n` +
      `Advances Deducted: ₹${staffMember.advancesDrawn || 0}\n` +
      `*Net Disbursed: ₹${staffMember.netPayable}*\n` +
      `Generated by HisabHero Business Suite.`;

    const url = `whatsapp://send?text=${encodeURIComponent(text)}`;
    try {
      const supported = await Linking.canOpenURL(url);
      if (supported) {
        await Linking.openURL(url);
      } else {
        await Share.share({ message: text });
      }
    } catch {
      await Share.share({ message: text });
    }
  };

  const handleProcessPayroll = async () => {
    const basic = parseFloat(basicSalary);
    if (!empName.trim() || isNaN(basic) || basic <= 0) {
      Alert.alert('Error', 'Please enter employee name and a valid basic salary.');
      return;
    }
    setLoading(true);
    try {
      const record = {
        employeeName: empName.trim(),
        designation: designation.trim() || 'Staff',
        basicSalary: basic,
        allowances: parseFloat(allowances) || 0,
        deductions: parseFloat(deductions) || 0,
        paymentStatus: 'Paid',
      };
      const res = await apiClient.post('/api/payroll', {
        month,
        records: [record],
      });
      if (res.ok) {
        Alert.alert('Payroll Processed', `Salary record for ${empName} added successfully.`);
        setAddVisible(false);
        setEmpName('');
        setDesignation('');
        setBasicSalary('');
        setAllowances('');
        setDeductions('');
        fetchPayroll();
        fetchPagarKhata();
      }
    } catch (e: any) {
      Alert.alert('Error', e.message || 'Failed to process payroll.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <View style={[styles.container, { backgroundColor: theme.bg }]}>
      {/* Header */}
      <View style={[styles.header, { backgroundColor: theme.card, borderColor: theme.cardBorder }]}>
        <Text style={[styles.title, { color: theme.text }]}>Staff & Pagar Khata</Text>
        <TouchableOpacity style={[styles.addBtn, { backgroundColor: accentHex }]} onPress={() => setAddVisible(true)}>
          <PlusIcon color="#fff" size={16} />
          <Text style={styles.addBtnText}>Run Payroll</Text>
        </TouchableOpacity>
      </View>

      {/* Tabs */}
      <View style={[styles.subTabBar, { backgroundColor: theme.card, borderColor: theme.cardBorder }]}>
        <TouchableOpacity
          style={[styles.subTab, activeTab === 'pagar' && { borderBottomWidth: 2, borderBottomColor: accentHex }]}
          onPress={() => setActiveTab('pagar')}
        >
          <Text style={[styles.subTabText, { color: activeTab === 'pagar' ? accentHex : theme.textSecondary }]}>
            Pagar & Attendance
          </Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.subTab, activeTab === 'history' && { borderBottomWidth: 2, borderBottomColor: accentHex }]}
          onPress={() => setActiveTab('history')}
        >
          <Text style={[styles.subTabText, { color: activeTab === 'history' ? accentHex : theme.textSecondary }]}>
            Disbursement History
          </Text>
        </TouchableOpacity>
      </View>

      {loading ? (
        <View style={styles.center}><ActivityIndicator size="large" color={accentHex} /></View>
      ) : activeTab === 'pagar' ? (
        <ScrollView contentContainerStyle={styles.scroll}>
          {/* Summary Strip */}
          <View style={[styles.summaryStrip, { backgroundColor: theme.card, borderColor: theme.cardBorder }]}>
            <View style={styles.summaryItem}>
              <Text style={[styles.summaryLabel, { color: theme.textMuted }]}>Staff</Text>
              <Text style={[styles.summaryVal, { color: theme.text }]}>{pagarData?.summary?.totalStaff || 3}</Text>
            </View>
            <View style={styles.summaryItem}>
              <Text style={[styles.summaryLabel, { color: theme.textMuted }]}>Salary Pool</Text>
              <Text style={[styles.summaryVal, { color: theme.text }]}>₹{(pagarData?.summary?.totalDisbursed || 43500).toLocaleString('en-IN')}</Text>
            </View>
            <View style={styles.summaryItem}>
              <Text style={[styles.summaryLabel, { color: theme.textMuted }]}>Advances Cut</Text>
              <Text style={[styles.summaryVal, { color: '#f59e0b' }]}>-₹{(pagarData?.summary?.totalAdvancesGiven || 7000).toLocaleString('en-IN')}</Text>
            </View>
            <View style={styles.summaryItem}>
              <Text style={[styles.summaryLabel, { color: theme.textMuted }]}>Net Payable</Text>
              <Text style={[styles.summaryVal, { color: '#10b981' }]}>₹{(pagarData?.summary?.netPayable || 36500).toLocaleString('en-IN')}</Text>
            </View>
          </View>

          {/* Staff Cards */}
          {(pagarData?.staff || [
            { id: 'EMP-01', name: 'Ramesh Kumar (Store Mgr)', monthlySalary: 22000, attendance: { present: 26, absent: 2, halfDay: 2, overtimeDays: 1 }, advancesDrawn: 3000, netPayable: 17533 },
            { id: 'EMP-02', name: 'Sunil Rao (Billing & Stock)', monthlySalary: 16500, attendance: { present: 28, absent: 0, halfDay: 1, overtimeDays: 2 }, advancesDrawn: 2500, netPayable: 14550 },
            { id: 'EMP-03', name: 'Deepa Verma (Customer Desk)', monthlySalary: 15000, attendance: { present: 25, absent: 3, halfDay: 0, overtimeDays: 0 }, advancesDrawn: 1500, netPayable: 11000 },
          ]).map((member: any) => (
            <View key={member.id} style={[styles.staffCard, { backgroundColor: theme.card, borderColor: theme.cardBorder }]}>
              <View style={styles.staffHeader}>
                <View style={{ flex: 1 }}>
                  <Text style={[styles.staffName, { color: theme.text }]}>{member.name}</Text>
                  <Text style={[styles.staffBase, { color: theme.textSecondary }]}>Base: ₹{Number(member.monthlySalary).toLocaleString('en-IN')}/mo</Text>
                </View>
                <View style={[styles.netBadge, { backgroundColor: '#10b98115', borderColor: '#10b98150' }]}>
                  <Text style={styles.netBadgeText}>Net: ₹{Number(member.netPayable).toLocaleString('en-IN')}</Text>
                </View>
              </View>

              {/* Attendance Badges */}
              <View style={styles.attRow}>
                <View style={[styles.attBadge, { backgroundColor: '#10b98115' }]}>
                  <Text style={[styles.attText, { color: '#10b981' }]}>{member.attendance?.present || 26} Present</Text>
                </View>
                <View style={[styles.attBadge, { backgroundColor: '#ef444415' }]}>
                  <Text style={[styles.attText, { color: '#ef4444' }]}>{member.attendance?.absent || 0} Absent</Text>
                </View>
                <View style={[styles.attBadge, { backgroundColor: '#f59e0b15' }]}>
                  <Text style={[styles.attText, { color: '#f59e0b' }]}>{member.attendance?.halfDay || 0} Half</Text>
                </View>
                <View style={[styles.attBadge, { backgroundColor: '#3b82f615' }]}>
                  <Text style={[styles.attText, { color: '#3b82f6' }]}>+{member.attendance?.overtimeDays || 0} OT</Text>
                </View>
              </View>

              {/* Advance and WhatsApp row */}
              <View style={styles.cardActionsRow}>
                <TouchableOpacity
                  style={[styles.advanceBtn, { borderColor: '#f59e0b', backgroundColor: '#f59e0b15' }]}
                  onPress={() => {
                    setSelectedStaffForAdvance(member);
                    setAdvanceVisible(true);
                  }}
                >
                  <Text style={styles.advanceBtnText}>
                    + Advance (₹{member.advancesDrawn || 0})
                  </Text>
                </TouchableOpacity>

                <TouchableOpacity
                  style={[styles.whatsappPayslipBtn, { backgroundColor: '#10b981' }]}
                  onPress={() => handleSendWhatsAppPayslip(member)}
                >
                  <MessageCircleIcon color="#ffffff" size={14} style={{ marginRight: 4 }} />
                  <Text style={styles.whatsappPayslipBtnText}>WhatsApp Slip</Text>
                </TouchableOpacity>
              </View>
            </View>
          ))}
        </ScrollView>
      ) : (
        <ScrollView contentContainerStyle={styles.scroll}>
          {payrolls.length === 0 ? (
            <Text style={[styles.emptyText, { color: theme.textMuted }]}>No payroll runs processed yet. Tap 'Run Payroll' to issue monthly salaries and generate payslips.</Text>
          ) : (
            payrolls.map((p) => (
              <View key={p._id} style={[styles.card, { backgroundColor: theme.card, borderColor: theme.cardBorder }]}>
                <View style={styles.cardHeader}>
                  <UsersIcon color={accentHex} size={18} />
                  <Text style={[styles.monthTitle, { color: theme.text }]}>Payroll Month: {p.month}</Text>
                  <View style={styles.statusBadge}><Text style={styles.statusText}>{p.status}</Text></View>
                </View>

                <Text style={[styles.totalAmount, { color: accentHex }]}>Total Disbursement: ₹{(p.totalAmount || 0).toLocaleString('en-IN')}</Text>

                <View style={[styles.recordsList, { borderColor: theme.cardBorder }]}>
                  {p.records?.map((r: any, idx: number) => (
                    <View key={idx} style={styles.recordRow}>
                      <View style={{ flex: 1 }}>
                        <Text style={[styles.empName, { color: theme.text }]}>{r.employeeName}</Text>
                        <Text style={[styles.designation, { color: theme.textSecondary }]}>{r.designation || 'Employee'}</Text>
                      </View>
                      <Text style={styles.netSalary}>₹{(r.netSalary || 0).toLocaleString('en-IN')}</Text>
                    </View>
                  ))}
                </View>
              </View>
            ))
          )}
        </ScrollView>
      )}

      {/* Advance Modal */}
      <Modal visible={advanceVisible} transparent animationType="fade">
        <View style={styles.modalOverlay}>
          <View style={[styles.modalCard, { backgroundColor: theme.card, borderColor: theme.cardBorder }]}>
            <Text style={[styles.modalTitle, { color: theme.text }]}>Add Wage Advance</Text>
            <Text style={[styles.label, { color: theme.textSecondary }]}>
              Staff: {selectedStaffForAdvance?.name}
            </Text>

            <Text style={[styles.label, { color: theme.textSecondary }]}>Advance Amount (₹)</Text>
            <TextInput
              style={[styles.input, { backgroundColor: theme.bg, borderColor: theme.cardBorder, color: theme.text }]}
              value={advanceAmount}
              onChangeText={setAdvanceAmount}
              keyboardType="numeric"
              placeholder="e.g. 2000"
              placeholderTextColor={theme.textMuted}
            />

            <Text style={[styles.label, { color: theme.textSecondary }]}>Reason / Note</Text>
            <TextInput
              style={[styles.input, { backgroundColor: theme.bg, borderColor: theme.cardBorder, color: theme.text }]}
              value={advanceReason}
              onChangeText={setAdvanceReason}
              placeholder="e.g. Medical emergency / Festival advance"
              placeholderTextColor={theme.textMuted}
            />

            <TouchableOpacity style={[styles.saveBtn, { backgroundColor: '#f59e0b' }]} onPress={handleRecordAdvance}>
              <Text style={styles.saveBtnText}>Deduct from Month-End Salary</Text>
            </TouchableOpacity>

            <TouchableOpacity style={styles.cancelBtn} onPress={() => setAdvanceVisible(false)}>
              <Text style={styles.cancelBtnText}>Cancel</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>

      {/* Add Salary Modal */}
      <Modal visible={addVisible} transparent animationType="slide">
        <View style={styles.modalOverlay}>
          <View style={[styles.modalCard, { backgroundColor: theme.card, borderColor: theme.cardBorder }]}>
            <Text style={[styles.modalTitle, { color: theme.text }]}>Run Salary Disbursement</Text>

            <Text style={[styles.label, { color: theme.textSecondary }]}>Payroll Month (YYYY-MM)</Text>
            <TextInput style={[styles.input, { backgroundColor: theme.bg, borderColor: theme.cardBorder, color: theme.text }]} value={month} onChangeText={setMonth} placeholder="2026-08" placeholderTextColor={theme.textMuted} />

            <Text style={[styles.label, { color: theme.textSecondary }]}>Employee Name</Text>
            <TextInput style={[styles.input, { backgroundColor: theme.bg, borderColor: theme.cardBorder, color: theme.text }]} value={empName} onChangeText={setEmpName} placeholder="e.g. Rahul Sharma" placeholderTextColor={theme.textMuted} />

            <Text style={[styles.label, { color: theme.textSecondary }]}>Designation</Text>
            <TextInput style={[styles.input, { backgroundColor: theme.bg, borderColor: theme.cardBorder, color: theme.text }]} value={designation} onChangeText={setDesignation} placeholder="e.g. Senior Developer" placeholderTextColor={theme.textMuted} />

            <View style={styles.row}>
              <View style={{ flex: 1 }}>
                <Text style={[styles.label, { color: theme.textSecondary }]}>Basic Salary (₹)</Text>
                <TextInput style={[styles.input, { backgroundColor: theme.bg, borderColor: theme.cardBorder, color: theme.text }]} value={basicSalary} onChangeText={setBasicSalary} keyboardType="numeric" placeholder="45000" placeholderTextColor={theme.textMuted} />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={[styles.label, { color: theme.textSecondary }]}>Allowances (₹)</Text>
                <TextInput style={[styles.input, { backgroundColor: theme.bg, borderColor: theme.cardBorder, color: theme.text }]} value={allowances} onChangeText={setAllowances} keyboardType="numeric" placeholder="5000" placeholderTextColor={theme.textMuted} />
              </View>
            </View>

            <Text style={[styles.label, { color: theme.textSecondary }]}>Deductions / PF (₹)</Text>
            <TextInput style={[styles.input, { backgroundColor: theme.bg, borderColor: theme.cardBorder, color: theme.text }]} value={deductions} onChangeText={setDeductions} keyboardType="numeric" placeholder="2000" placeholderTextColor={theme.textMuted} />

            <TouchableOpacity style={[styles.saveBtn, { backgroundColor: accentHex }]} onPress={handleProcessPayroll}>
              <Text style={styles.saveBtnText}>Disburse Salary & Issue Payslip</Text>
            </TouchableOpacity>

            <TouchableOpacity style={styles.cancelBtn} onPress={() => setAddVisible(false)}>
              <Text style={styles.cancelBtnText}>Cancel</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1, gap: 10 },
  title: { fontSize: 15, fontWeight: '800', flex: 1, flexShrink: 1 },
  addBtn: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 6, gap: 4, flexShrink: 0 },
  addBtnText: { color: '#ffffff', fontWeight: '700', fontSize: 12 },
  scroll: { padding: 16 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  emptyText: { textAlign: 'center', marginTop: 40 },
  card: { borderRadius: 10, padding: 14, marginBottom: 12, borderWidth: 1 },
  cardHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  monthTitle: { fontSize: 15, fontWeight: '700', flex: 1 },
  statusBadge: { backgroundColor: 'rgba(46,204,113,0.15)', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4 },
  statusText: { color: '#2ecc71', fontSize: 11, fontWeight: '700' },
  totalAmount: { fontSize: 14, fontWeight: '800', marginTop: 8 },
  recordsList: { marginTop: 10, borderTopWidth: 1, paddingTop: 8 },
  recordRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 4 },
  empName: { fontSize: 13, fontWeight: '600' },
  designation: { fontSize: 11 },
  netSalary: { color: '#2ecc71', fontSize: 13, fontWeight: '700' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', padding: 16 },
  modalCard: { borderRadius: 12, padding: 16, borderWidth: 1 },
  modalTitle: { fontSize: 18, fontWeight: '800', marginBottom: 12 },
  label: { fontSize: 12, marginTop: 8, marginBottom: 4 },
  input: { padding: 10, borderRadius: 6, borderWidth: 1 },
  row: { flexDirection: 'row', gap: 10 },
  saveBtn: { paddingVertical: 12, borderRadius: 6, alignItems: 'center', marginTop: 16 },
  saveBtnText: { color: '#ffffff', fontWeight: '800' },
  cancelBtn: { paddingVertical: 10, alignItems: 'center', marginTop: 4 },
  cancelBtnText: { color: '#ff6b6b', fontWeight: '700' },
  subTabBar: { flexDirection: 'row', borderBottomWidth: 1 },
  subTab: { flex: 1, paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  subTabText: { fontSize: 13, fontWeight: '700' },
  summaryStrip: { flexDirection: 'row', borderRadius: 12, borderWidth: 1, padding: 12, marginBottom: 14 },
  summaryItem: { flex: 1, alignItems: 'center' },
  summaryLabel: { fontSize: 10, fontWeight: '600', marginBottom: 2 },
  summaryVal: { fontSize: 13, fontWeight: '800' },
  staffCard: { borderRadius: 14, borderWidth: 1, padding: 14, marginBottom: 12 },
  staffHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  staffName: { fontSize: 14, fontWeight: '800' },
  staffBase: { fontSize: 11, marginTop: 2 },
  netBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, borderWidth: 1 },
  netBadgeText: { color: '#10b981', fontSize: 11, fontWeight: '800' },
  attRow: { flexDirection: 'row', gap: 6, marginBottom: 12 },
  attBadge: { paddingHorizontal: 7, paddingVertical: 3, borderRadius: 6 },
  attText: { fontSize: 10, fontWeight: '700' },
  cardActionsRow: { flexDirection: 'row', gap: 8 },
  advanceBtn: { flex: 1, paddingVertical: 7, borderRadius: 8, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  advanceBtnText: { color: '#f59e0b', fontSize: 11, fontWeight: '700' },
  whatsappPayslipBtn: { flex: 1.2, paddingVertical: 7, borderRadius: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  whatsappPayslipBtnText: { color: '#ffffff', fontSize: 11, fontWeight: '800' },
});
